// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/whj1990/app-mine/rpc"
	"github.com/whj1990/bff-mine/internal/handler"
	"github.com/whj1990/bff-mine/internal/router"
	"github.com/whj1990/go-core/launch"
)

import (
	_ "github.com/whj1990/bff-mine/docs"
)

// Injectors from wire.go:

func initServer() *launch.RouterQuote {
	client := rpc.NewMineClient()
	mineHandler := handler.NewMineHandler(client)
	routerMineHandler := router.NewMinelRouter(mineHandler)
	routerQuote := newRouterQuote(routerMineHandler)
	return routerQuote
}
